# Generated by Django 3.2 on 2022-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_avaliacao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='username',
            field=models.CharField(max_length=105, verbose_name='Username'),
        ),
    ]
